[project]
name = "proxy-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["requests>=2.31", "aiohttp>=3.9", "fastapi>=0.115", "uvicorn[standard]>=0.34"]
